ALTER TABLE nodes ADD COLUMN IF NOT EXISTS data_root TEXT NOT NULL DEFAULT '/var/lib/clarklab/services';
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS data_root_migrate BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS reported_data_root TEXT NOT NULL DEFAULT '';
