ALTER TABLE platform_settings
  ADD COLUMN IF NOT EXISTS auto_update_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS auto_update_poll_seconds INT NOT NULL DEFAULT 300,
  ADD COLUMN IF NOT EXISTS auto_update_api BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS auto_update_agents BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS automation_github_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS last_deployed_commit_sha TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_auto_check_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS github_webhook_secret TEXT NOT NULL DEFAULT '';
